import = ["~/.config/alacritty/themes/themes/everforest_dark.toml"]

[window]
decorations = "None"
blur = true
startup_mode = "Maximized"

[font]
size = 16

[env]
TERM = "xterm-256color"

# [shell]
# program = "tmux"

# correct alacritty key-code, so that neovim mappings can work normally.
[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"
